# Generated by Django 2.2.4 on 2019-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_documents',
            field=models.FileField(null=True, upload_to='uploaded_documents/'),
        ),
    ]
