# Generated by Django 2.2.4 on 2019-08-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_app', '0002_task_task_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_documents',
        ),
    ]
