# Generated by Django 2.2.4 on 2019-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_app', '0004_taskfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='single_spaced',
            field=models.BooleanField(default=False, verbose_name='single spaced'),
        ),
    ]
